class payment{
     isSuccessful = false
     transactionRef = ""
     payment(data){
         //Do all payment initialization here
     }
     verifyPayment(transRef){
         //Do payment verification here
         //If successful set isSuccessfull to true;
         //& set transactionRef to the transaction reference generated by the payment gateway
     }
}

module.exports = payment;